---
title: "Homework 06: Data wrangling wrap up"
output:
  html_document:
    keep_md: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: united
---


```r
# load required libraries
suppressPackageStartupMessages(library(gapminder))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(repurrrsive))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(singer))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggmap))
```


# Task 2: Writing functions
In this part, as suggested by the instructor, I will follow the linear regreation function posted [here](http://stat545.com/block012_function-regress-lifeexp-on-year.html) and generalize the quadratic regression function.


## 2.1 Compute the data on mini data frame corresponding to one country 

```r
j_country <- "China"
j_dat <- gapminder %>% 
  filter(country == j_country)
# take a glance at filtered data frame
knitr::kable(j_dat, align = 'c')
```



 country    continent    year    lifeExp        pop        gdpPercap 
---------  -----------  ------  ----------  ------------  -----------
  China       Asia       1952    44.00000    556263527     400.4486  
  China       Asia       1957    50.54896    637408000     575.9870  
  China       Asia       1962    44.50136    665770000     487.6740  
  China       Asia       1967    58.38112    754550000     612.7057  
  China       Asia       1972    63.11888    862030000     676.9001  
  China       Asia       1977    63.96736    943455000     741.2375  
  China       Asia       1982    65.52500    1000281000    962.4214  
  China       Asia       1987    67.27400    1084035000    1378.9040 
  China       Asia       1992    68.69000    1164970000    1655.7842 
  China       Asia       1997    70.42600    1230075000    2289.2341 
  China       Asia       2002    72.02800    1280400000    3119.2809 
  China       Asia       2007    72.96100    1318683096    4959.1149 

To do the quadratic regression, a square term is included. Always plot the data:

```r
p <- ggplot(j_dat, aes(x = year, y = lifeExp))
p + 
  geom_point() + 
  # uses the I() function to protect the expression inside, I ensure it is interpreted in the obvious arithmetical way.
  geom_smooth(method = "lm", formula = y ~ x + I(x^2)) + 
  ggtitle("Quadratic regression of China's lifeExp over the years") + 
  ylab("Life Expectancy") + 
  theme_bw()
```

![](hw06_files/figure-html/Part 2-1-1.png)<!-- -->

Fit the regression:

```r
j_fit <- lm(lifeExp ~ (year + I(year^2)), j_dat)
coef(j_fit)
```

```
##   (Intercept)          year     I(year^2) 
## -3.471471e+04  3.460852e+01 -8.607680e-03
```

The interception basically tells the life expectancy of China at year 0 and the value is negative which doesn't make any sense. I think it makes more sense for the intercept to correspond to life expectancy in 1952, the earliest date in our dataset instead. Change the model:

```r
p <- ggplot(j_dat, aes(x = year, y = lifeExp))
p + 
  geom_point() + 
  # uses the I() function to protect the expression inside, I ensure it is interpreted in the obvious arithmetical way.
  geom_smooth(method = "lm", formula = y ~ I(x - 1952) + I(x^2 - 1952^2)) + 
  ggtitle("Quadratic regression of China's lifeExp over the years modified") + 
  ylab("Life Expectancy") + 
  theme_bw()
```

![](hw06_files/figure-html/Part 2-2-1.png)<!-- -->

Fit the regression:

```r
j_fit <- lm(lifeExp ~ I(year - 1952) + I(year^2 - 1952^2), data = j_dat)

coef(j_fit)  # coefficients of the model
```

```
##        (Intercept)     I(year - 1952) I(year^2 - 1952^2) 
##        43.24529473        34.60852124        -0.00860768
```
Now the interception is the life expectancy of China around year 1952 and it is 43.24.


## 2.2 Turn working code into a function.
Create le_quad_fit() to get the model coefficient given data frame as input:

```r
le_quad_fit <- function(dat, offset = 1952) {
  the_fit <- lm(lifeExp ~ I(year - offset) + I(year ^ 2 - offset ^ 2), dat)
  # set names on the return values
  setNames(coef(the_fit), c("intercept", "slope", "quadratic"))
}
le_quad_fit(j_dat)
```

```
##   intercept       slope   quadratic 
## 43.24529473 34.60852124 -0.00860768
```

Also we can make le_quad_plot() function for quadratic plot into function with given data frame as input:

```r
le_quad_plot <- function(dat, offset = 1952, country) {
  p <- ggplot(dat, aes(x = year, y = lifeExp))
  p + 
    geom_point() + 
    # uses the I() function to protect the expression inside, I ensure it is interpreted in the obvious   arithmetical way.
    geom_smooth(method = "lm", formula = y ~ I(x - 1952) + I(x^2 - 1952^2)) + 
    ggtitle(paste("Quadratic regression of", country, "life expectancy over the years by function")) + 
    ylab("Life Expectancy") + 
    theme_bw()
}
le_quad_plot(j_dat, country = "China")
```

![](hw06_files/figure-html/Part 2-3-1.png)<!-- -->


## 2.3 Test on other data
Now we can use `le_quad_plot()` to plot the quadratic regression model of a certain country and `le_quad_fit()` to get the coefficients of model of certain country.

Let's try with Japan:

```r
japan_data <- gapminder %>% filter(country == "Japan")
le_quad_plot(japan_data, country = "Japan")
```

![](hw06_files/figure-html/Part 2-4-1.png)<!-- -->

```r
le_quad_fit(japan_data)
```

```
##   intercept       slope   quadratic 
## 62.99542582 18.72230824 -0.00463991
```

More tests on India:


```r
india_data <- gapminder %>% filter(country == "India")
le_quad_plot(india_data, country = "India")
```

![](hw06_files/figure-html/Part 2-5-1.png)<!-- -->

```r
le_quad_fit(india_data)
```

```
##    intercept        slope    quadratic 
## 36.643140110 23.193555015 -0.005730799
```

for comparison, the linear regression model with india data is plotted: 

```r
india_data %>% 
  ggplot(aes(year, lifeExp)) + 
  geom_point() + 
  geom_smooth(aes(color = "linear regression"), 
              method = "lm", 
              se = FALSE) +
  geom_smooth(aes(color = "quadratic regression"), 
              method = "lm", 
              formula = y ~ I(x - 1952) + I(x^2 - 1952^2)) + 
  ggtitle("Linear fitting of India's life expectancy vs year") + 
  ylab("Life Expectancy") + 
  theme_bw()
```

![](hw06_files/figure-html/Part 2-6-1.png)<!-- -->

We can see that the quadratic model does a better job in fitting. Thus, our function of quadratic regression gains a better result than built-in linear regression fitting.


# Task 4: Work with the singer data

## 4.1 Use purrr to map latitude and longitude into human readable information on the band’s origin places.
For this part, we need to enable the google API key:

```r
register_google("AIzaSyCofrdT-5MetLRbrW9Rt-l50gAeEr3eCNY")
```

First, take a look at singer_locations data frame.

```r
str(singer_locations)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	10100 obs. of  14 variables:
##  $ track_id          : chr  "TRWICRA128F42368DB" "TRXJANY128F42246FC" "TRIKPCA128F424A553" "TRYEATD128F92F87C9" ...
##  $ title             : chr  "The Conversation (Cd)" "Lonely Island" "Here's That Rainy Day" "Rego Park Blues" ...
##  $ song_id           : chr  "SOSURTI12A81C22FB8" "SODESQP12A6D4F98EF" "SOQUYQD12A8C131619" "SOEZGRC12AB017F1AC" ...
##  $ release           : chr  "Even If It Kills Me" "The Duke Of Earl" "Imprompture" "Still River" ...
##  $ artist_id         : chr  "ARACDPV1187FB58DF4" "ARYBUAO1187FB3F4EB" "AR4111G1187B9B58AB" "ARQDZP31187B98D623" ...
##  $ artist_name       : chr  "Motion City Soundtrack" "Gene Chandler" "Paul Horn" "Ronnie Earl & the Broadcasters" ...
##  $ year              : int  2007 2004 1998 1995 1968 2006 2003 2007 1966 2006 ...
##  $ duration          : num  170 107 528 695 237 ...
##  $ artist_hotttnesss : num  0.641 0.394 0.431 0.362 0.411 ...
##  $ artist_familiarity: num  0.823 0.57 0.504 0.477 0.53 ...
##  $ latitude          : num  NA 41.9 40.7 NA 42.3 ...
##  $ longitude         : num  NA -87.6 -74 NA -83 ...
##  $ name              : chr  NA "Gene Chandler" "Paul Horn" NA ...
##  $ city              : chr  NA "Chicago, IL" "New York, NY" NA ...
##  - attr(*, "spec")=List of 2
##   ..$ cols   :List of 14
##   .. ..$ track_id          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ title             : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ song_id           : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ release           : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ artist_id         : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ artist_name       : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ year              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
##   .. ..$ duration          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ artist_hotttnesss : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ artist_familiarity: list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ latitude          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ longitude         : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ name              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ city              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   ..$ default: list()
##   .. ..- attr(*, "class")= chr  "collector_guess" "collector"
##   ..- attr(*, "class")= chr "col_spec"
```

```r
knitr::kable(head(singer_locations))
```



track_id             title                   song_id              release               artist_id            artist_name                       year   duration   artist_hotttnesss   artist_familiarity   latitude   longitude  name            city         
-------------------  ----------------------  -------------------  --------------------  -------------------  -------------------------------  -----  ---------  ------------------  -------------------  ---------  ----------  --------------  -------------
TRWICRA128F42368DB   The Conversation (Cd)   SOSURTI12A81C22FB8   Even If It Kills Me   ARACDPV1187FB58DF4   Motion City Soundtrack            2007   170.4485           0.6410183            0.8230522         NA          NA  NA              NA           
TRXJANY128F42246FC   Lonely Island           SODESQP12A6D4F98EF   The Duke Of Earl      ARYBUAO1187FB3F4EB   Gene Chandler                     2004   106.5530           0.3937627            0.5700167   41.88415   -87.63241  Gene Chandler   Chicago, IL  
TRIKPCA128F424A553   Here's That Rainy Day   SOQUYQD12A8C131619   Imprompture           AR4111G1187B9B58AB   Paul Horn                         1998   527.5947           0.4306226            0.5039940   40.71455   -74.00712  Paul Horn       New York, NY 
TRYEATD128F92F87C9   Rego Park Blues         SOEZGRC12AB017F1AC   Still River           ARQDZP31187B98D623   Ronnie Earl & the Broadcasters    1995   695.1179           0.3622792            0.4773099         NA          NA  NA              NA           
TRBYYXH128F4264585   Games                   SOPIOCP12A8C13A322   Afro-Harping          AR75GYU1187B9AE47A   Dorothy Ashby                     1968   237.3220           0.4107520            0.5303468   42.33168   -83.04792  Dorothy Ashby   Detroit, MI  
TRKFFKR128F9303AE3   More Pipes              SOHQSPY12AB0181325   Six Yanks             ARCENE01187B9AF929   Barleyjuice                       2006   192.9400           0.3762635            0.5412950   40.99471   -77.60454  Barleyjuice     Pennsylvania 


```r
singer_trunc <- singer_locations %>% 
  select(latitude, longitude, city)
knitr::kable(head(singer_trunc, 10))
```



 latitude   longitude  city         
---------  ----------  -------------
       NA          NA  NA           
 41.88415   -87.63241  Chicago, IL  
 40.71455   -74.00712  New York, NY 
       NA          NA  NA           
 42.33168   -83.04792  Detroit, MI  
 40.99471   -77.60454  Pennsylvania 
       NA          NA  NA           
       NA          NA  NA           
       NA          NA  NA           
       NA          NA  NA           

We can see that some of the tracks have missing data. Filter those tracks which miss city, the latitude and longitude:

```r
singer_trunc <- singer_trunc %>% filter(!is.na(latitude) & !is.na(longitude) & !is.na(city))
knitr::kable(head(singer_trunc, 10))
```



 latitude    longitude  city              
---------  -----------  ------------------
 41.88415    -87.63241  Chicago, IL       
 40.71455    -74.00712  New York, NY      
 42.33168    -83.04792  Detroit, MI       
 40.99471    -77.60454  Pennsylvania      
 34.20034   -119.18044  Oxnard, CA        
 50.73230      7.10169  Bonn              
 19.59009   -155.43414  Hawaii            
 34.05349   -118.24532  Los Angeles, CA   
 40.57250    -74.15400  Staten Island, NY 
 45.51179   -122.67563  Portland, OR      

Let's take a look at singer_trunc first.

```r
str(singer_trunc)
```

```
## Classes 'tbl_df', 'tbl' and 'data.frame':	4129 obs. of  3 variables:
##  $ latitude : num  41.9 40.7 42.3 41 34.2 ...
##  $ longitude: num  -87.6 -74 -83 -77.6 -119.2 ...
##  $ city     : chr  "Chicago, IL" "New York, NY" "Detroit, MI" "Pennsylvania" ...
##  - attr(*, "spec")=List of 2
##   ..$ cols   :List of 14
##   .. ..$ track_id          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ title             : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ song_id           : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ release           : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ artist_id         : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ artist_name       : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ year              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
##   .. ..$ duration          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ artist_hotttnesss : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ artist_familiarity: list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ latitude          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ longitude         : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ name              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ city              : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   ..$ default: list()
##   .. ..- attr(*, "class")= chr  "collector_guess" "collector"
##   ..- attr(*, "class")= chr "col_spec"
```

After taking a look at singer_trunc data frame, it has 4129 rows. For the demo of ggmap, we will work on the first 20 sets of data instead.

```r
singer_trunc_20 <- singer_trunc %>% 
  slice(1:20)

# use revgeocode to get city location by given longitude and latitude
ggmap_res <- mapply(FUN = function(lon, lat) { 
  revgeocode(c(lon, lat), output = "address") 
  }, 
  singer_trunc_20$longitude, singer_trunc_20$latitude
  )
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=41.88415,-87.63241&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.71455,-74.00712&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=42.33168,-83.04792&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.99471,-77.60454&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=34.20034,-119.18044&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=50.7323,7.10169&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=19.59009,-155.43414&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=34.05349,-118.24532&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.5725,-74.154&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=45.51179,-122.67563&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=51.50632,-0.12714&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=42.50172,12.88512&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.43831,-79.99745&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.71455,-74.00712&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=37.77916,-122.42005&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.71455,-74.00712&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=34.05349,-118.24532&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=37.27188,-119.27023&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=8.4177,-80.11278&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

```
## Source : https://maps.googleapis.com/maps/api/geocode/json?latlng=47.38028,-122.23742&key=xxx-5MetLRbrW9Rt-l50gAeEr3eCNY
```

Take a look at first 10 rows of resulting location list by ggmap:

```r
head(ggmap_res, 10)
```

```
##  [1] "134 N LaSalle St suite 1720, Chicago, IL 60602, USA"
##  [2] "80 Chambers St, New York, NY 10007, USA"            
##  [3] "1001 Woodward Ave, Detroit, MI 48226, USA"          
##  [4] "Z. H. Confair Memorial Hwy, Howard, PA 16841, USA"  
##  [5] "300 W 3rd St, Oxnard, CA 93030, USA"                
##  [6] "Regina-Pacis-Weg 1, 53113 Bonn, Germany"            
##  [7] "Unnamed Road, Hawaii, USA"                          
##  [8] "1420 S Oakhurst Dr, Los Angeles, CA 90035, USA"     
##  [9] "215 Arthur Kill Rd, Staten Island, NY 10306, USA"   
## [10] "1500 SW 1st Ave, Portland, OR 97201, USA"
```

The table for comparing cities from singer_location and ggmap extracted cities with longitude and latitude can be generated.

```r
knitr::kable(cbind(ggmap_res, singer_trunc_20$city),
             col.names = c("ggmap extracted cities", "cities in singer_location"),
             align = "c")
```

                  ggmap extracted cities                      cities in singer_location   
----------------------------------------------------------  ------------------------------
   134 N LaSalle St suite 1720, Chicago, IL 60602, USA               Chicago, IL          
         80 Chambers St, New York, NY 10007, USA                     New York, NY         
        1001 Woodward Ave, Detroit, MI 48226, USA                    Detroit, MI          
    Z. H. Confair Memorial Hwy, Howard, PA 16841, USA                Pennsylvania         
           300 W 3rd St, Oxnard, CA 93030, USA                        Oxnard, CA          
         Regina-Pacis-Weg 1, 53113 Bonn, Germany                         Bonn             
                Unnamed Road, Hawaii, USA                               Hawaii            
      1420 S Oakhurst Dr, Los Angeles, CA 90035, USA               Los Angeles, CA        
     215 Arthur Kill Rd, Staten Island, NY 10306, USA             Staten Island, NY       
         1500 SW 1st Ave, Portland, OR 97201, USA                    Portland, OR         
      39 Whitehall, Westminster, London SW1A 2BY, UK            UK - England - London     
   Localita' Pescatore, Poggio Bustone, RI 02018, Italy      Poggio Bustone, Rieti, Italy 
         410 Grant St, Pittsburgh, PA 15219, USA                    Pittsburgh, PA        
         80 Chambers St, New York, NY 10007, USA                     New York, NY         
 1 Dr Carlton B Goodlett Pl, San Francisco, CA 94102, USA            New York, NY         
         80 Chambers St, New York, NY 10007, USA                     New York, NY         
      1420 S Oakhurst Dr, Los Angeles, CA 90035, USA               Los Angeles, CA        
                Shaver Lake, CA 93634, USA                            California          
             Calle Aviacion, Río Hato, Panama                           Panama            
            220 4th Ave S, Kent, WA 98032, USA                     KENT, WASHINGTON       


## 4.2 Try to check whether the place in city corresponds to the information you retrieved.

`grepl()` can be used to check if the first string contains the second string

```r
# apply grepl() over the list
mapply(grepl, singer_trunc_20$city, ggmap_res, fixed = TRUE)
```

```
##                  Chicago, IL                 New York, NY 
##                         TRUE                         TRUE 
##                  Detroit, MI                 Pennsylvania 
##                         TRUE                        FALSE 
##                   Oxnard, CA                         Bonn 
##                         TRUE                         TRUE 
##                       Hawaii              Los Angeles, CA 
##                         TRUE                         TRUE 
##            Staten Island, NY                 Portland, OR 
##                         TRUE                         TRUE 
##        UK - England - London Poggio Bustone, Rieti, Italy 
##                        FALSE                        FALSE 
##               Pittsburgh, PA                 New York, NY 
##                         TRUE                         TRUE 
##                 New York, NY                 New York, NY 
##                        FALSE                         TRUE 
##              Los Angeles, CA                   California 
##                         TRUE                        FALSE 
##                       Panama             KENT, WASHINGTON 
##                         TRUE                        FALSE
```

From the result, we can see some of them are not matching each other. However, take a closer look at two city lists, the format are not actually the same for ggmap and singer_locations. To determine if the city names match or not, changing format is necessary.


```r
# create function for split string by word for given list
split_word <- function(list) {
   r <- str_split(list, pattern = boundary("word"))
  return(r)
}

ggmap_city <- split_word(ggmap_res)
singer_city <- split_word(singer_trunc_20$city)

mapply(intersect, singer_city, ggmap_city) %>% 
  # get the length of intersection
  lapply(length) %>% 
  # if length of intersection is 0, then they don't match
  map(function(len) len > 0)
```

```
## [[1]]
## [1] TRUE
## 
## [[2]]
## [1] TRUE
## 
## [[3]]
## [1] TRUE
## 
## [[4]]
## [1] FALSE
## 
## [[5]]
## [1] TRUE
## 
## [[6]]
## [1] TRUE
## 
## [[7]]
## [1] TRUE
## 
## [[8]]
## [1] TRUE
## 
## [[9]]
## [1] TRUE
## 
## [[10]]
## [1] TRUE
## 
## [[11]]
## [1] TRUE
## 
## [[12]]
## [1] TRUE
## 
## [[13]]
## [1] TRUE
## 
## [[14]]
## [1] TRUE
## 
## [[15]]
## [1] FALSE
## 
## [[16]]
## [1] TRUE
## 
## [[17]]
## [1] TRUE
## 
## [[18]]
## [1] FALSE
## 
## [[19]]
## [1] TRUE
## 
## [[20]]
## [1] FALSE
```

From the result, we can see that most of the result match now. However, for 4th row, ggmap returns Z. H. Confair Memorial Hwy, Howard, PA 16841 USA	 and in singer_locations it shows Pennsylvania instead. The same failure appears for 18th row. To match those ones, all the states' names need to be matched with their abbreviations. 


## 4.3 If you still have time, you can go visual

```r
singer_trunc_20 %>%  
  leaflet()  %>%   
  addTiles() %>%  
  addCircles(lng = singer_trunc_20$longitude,
             lat = singer_trunc_20$latitude,
             popup = singer_trunc_20$city
            )
```

<!--html_preserve--><div id="htmlwidget-9dc78be0f7777ed9ffed" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-9dc78be0f7777ed9ffed">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addCircles","args":[[41.88415,40.71455,42.33168,40.99471,34.20034,50.7323,19.59009,34.05349,40.5725,45.51179,51.50632,42.50172,40.43831,40.71455,37.77916,40.71455,34.05349,37.27188,8.4177,47.38028],[-87.63241,-74.00712,-83.04792,-77.60454,-119.18044,7.10169,-155.43414,-118.24532,-74.154,-122.67563,-0.12714,12.88512,-79.99745,-74.00712,-122.42005,-74.00712,-118.24532,-119.27023,-80.11278,-122.23742],10,null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.2},["Chicago, IL","New York, NY","Detroit, MI","Pennsylvania","Oxnard, CA","Bonn","Hawaii","Los Angeles, CA","Staten Island, NY","Portland, OR","UK - England - London","Poggio Bustone, Rieti, Italy","Pittsburgh, PA","New York, NY","New York, NY","New York, NY","Los Angeles, CA","California","Panama","KENT, WASHINGTON"],null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[8.4177,51.50632],"lng":[-155.43414,12.88512]}},"evals":[],"jsHooks":[]}</script><!--/html_preserve-->
With the `popup` option, when the circles are clicked, the corresponding city name will pop up on the map.
